  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  redis-test:
    container_name: redis-test_container
    build: .
    ports:
      - "8080:8080"
    ports:
      - 8080:8082
    links:
      - redis
