version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    image: "maven:3.5.2-jdk-8-alpine"
    expose:
      - "8080"
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - m2-repo:/data/.m2/repository
    links:
      - redis
    command: mvn install spring-boot:run
volumes:
  m2-repo:
